name: test replacing
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  other:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Replace tokens
        uses: CodeByJacob/replacePlaceholders@features
        with:
          files: "[test.json,text.txt]"
        env: 
          HELLO: "__hello_world__"
          WORLD: "any_other_world"
          TEST: "test value"

      - name: Check content
        run: cat text.txt
        shell: bash
