name: test replacing
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  other:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Replace tokens
        uses: CodeByJacob/replacePlaceholders@main
        with:
          input_file: text.txt
