name: test replacing
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  other:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Replace tokens
        uses: CodeByJacob/replacePlaceholders@main
        with:
          file: text.txt
        env: 
          HELLO: "__hello_world__"

      - name: Check content
        run: cat text.txt
        shell: bash
