name: test replacing
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  other:
    runs-on: ubuntu-latest
    steps:
      - uses: CodeByJacob/replacePlaceholders@main
        env:
          HELLO: "__hello__"
          world: "world"
        with:
          input_file: text.txt