name: test replacing
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: CodeByJacob/replacePlaceholders@main
        env:
          HELLO: "__hello__"


