name: test replacing
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    uses: CodeByJacob/replacePlaceholders@main
    with:
      input_file: "text.txt"
    env:
      HELLO: "_hello_"

